[package]
name = "cizrna"
authors = ["Marek Suchánek <msuchane@redhat.com>"]
version = "0.1.0"
edition = "2021"
description = "Generate an AsciiDoc release notes document from tracking tickets."
license = "GPL-3.0-or-later"
readme = "README.adoc"
categories = ["command-line-utilities", "text-processing", "template-engine"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "^3", features = ["cargo"] }
log = "0.4"
simplelog = "0.11"
restson = "^1.0"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "1.0"
serde_yaml = "0.8"
bugzilla_query = { path = "../bugzilla_query" }
jira_query = { path = "../jira_query" }
