[package]
name = "cizrna"
authors = ["Marek Suchánek <msuchane@redhat.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "^3", features = ["cargo"] }
# jira-query = { path = "../jira-query" }
restson = "^1.0"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "1.0"
